USE [master]
GO

/****** Object:  Database [integrador]    Script Date: 03/02/2020 07:25:53 a.m. ******/
CREATE DATABASE [integrador] ON  PRIMARY 
( NAME = N'integrador', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\integrador.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'integrador_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\integrador_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [integrador].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [integrador] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [integrador] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [integrador] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [integrador] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [integrador] SET ARITHABORT OFF 
GO

ALTER DATABASE [integrador] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [integrador] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [integrador] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [integrador] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [integrador] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [integrador] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [integrador] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [integrador] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [integrador] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [integrador] SET  ENABLE_BROKER 
GO

ALTER DATABASE [integrador] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [integrador] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [integrador] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [integrador] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [integrador] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [integrador] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [integrador] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [integrador] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [integrador] SET  MULTI_USER 
GO

ALTER DATABASE [integrador] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [integrador] SET DB_CHAINING OFF 
GO

ALTER DATABASE [integrador] SET  READ_WRITE 
GO

