//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hardcodeConsola
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IDUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int Edad { get; set; }
        public int IDTipoUsuario { get; set; }
        public bool Estado { get; set; }
    
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
